language: java
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: vladislavsevruk
    token:
      secure: Cd52Rumv53SdHdg6WOTSvtKGTC7XpYybAw49yNk7mBtSli0BKffbaRuExOr3aQwNyQUzIUhYpMmFCamNHq39MR0/1td9sYNY3brI2z/BvGG75qKe+bzeG47LHDiYZcKK4KaEwe+HnmDHkZg4woQoGdUjTZQ4d5v/HGg9kjXNrbzDEaxxwg9mTmFcJR1AjeqCYmlyDgNYDOeesU3/kyHaPGHTtbFmppmv+H5DGgzqR2qtinDYyXjrh4Zpr+o4PGaiMKr0fqLv6/KPzfU23Y8wjKP99bOYdFatay2lgnhrtA+lsMAL55h4xZ9M0/O/ogG638LrwLHFxTXCWp1NykPyJDAGZT3P6T8cW80HPl/V0Bmm1fw4IhO6C5fTZtiEYt2bOARSEulkCMU8J/C1+IBeF70yL4RBHszXM+nVIRwx3R1cX0ynzbeE2fcK0BgmnuqJklxGTo5pg5Z+oT1AsLcY2rAbeJau9cOJz5XYIOj2rWvlLp1GWqYJAT7yNd2xjxTxlWPd2qf4FUQXmz2FPsIbVM7S62BwNMkIuflV6jiS3w9UTzX0Fpch7Upv+P+nYgKT++6cCsNZ4Uhd3LgDVXEopY60Ealmv89SV6Ncw9qtEzbmr1I5BCjKzCublEE3LA1q7xy/QoKrBQbdTxP7ng594VEZ2CYfME4TbE1bidEvX3k=
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - ./gradlew clean jacocoTestReport sonarqube
  - ./gradlew build --scan -s